services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    volumes:
      - ${DATA_DIR}:/app/backend/data
    restart: always

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    depends_on:
      - app